### PR TITLE
Added fix for heatmap

### PR DESCRIPTION
**Pull request by ogibson**
# Background
#### Link to issue 

Heatmap failing

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ X] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [X ] Photo of a cute animal attached to this PR

image

### CODE REVIEW

**Review by marcellp — CHANGES_REQUESTED** [review]
The picture submitted as part of this merge request is a [Paramecium](https://en.wikipedia.org/wiki/Paramecium), which is an alveolate.

Alveolates are eukaryotes but belong to a separate taxonomical supergroup to the animal kingdom. While I cannot deny the cuteness of the picture presented, the picture must be of an animal per the submission instructions. Please fix the submission template accordingly.

**Comment by ogibson** [comment]
I'm sorry about that Marcell, fixing it right now. Slight cladistic confusion, it derived from the fact that in zoology I studied protozoans together with animals.

**Review by ogibson — COMMENTED** [review]
Nevertheless, I think we need to broaden our definition from _animalia_ to [Holozoa](https://en.wikipedia.org/wiki/Holozoa). I'll create a ticket for that.

**Review by marcellp — DISMISSED** [review]

**Review by alexvpickering — APPROVED** [review]
Looks good, works locally on my box.

**Pull request merged**
